### ISSUE TITLE
Problème avec les heures

### ISSUE THREAD

**Issue by querel-lucie** [wleberre/gestimes#1]
Dès début 2018 il y a eu des problèmes avec les heures supp, en début de semaines les utilisateurs se retrouvaient avec -25h et au fur et à mesure où on ajoutait nos heures dans la semaine les heures supp augmentait c'est à dire qu'à la fin de la semaine on pouvait se retrouver avec 5h supp.

**Comment by Serizao** [comment]
https://github.com/wleberre/gestimes/commit/86db6e2f923157be47ceb19702d24e6370ec328f
I have patch this
