### ISSUE TITLE
Problème heures supp

### ISSUE THREAD

**Issue by querel-lucie** [wleberre/gestimes#2]
Bonjour William,

J'ai mis à jour ce que tu as fait ça a bien marché. Le seul problème c'est que les utilisateurs devrait avoir plus d'heures supp qu'ils en ont. Par exemple pour un utilisateur c'est marqué 40 heures supp sur gestime alors qu'il devrait en avoir 80. Un autre il en a 20 alors qu'il devrait en avoir 37... 
Dis moi si t'as besoin de fichiers 

Lucie

**Comment by Serizao** [comment]
Salut,

peux tu me fournir un moyen de reproduire l'erreur 
merci,

William

**Comment by querel-lucie** [comment]
Salut,

Etant donné que nous ne voyons pas où est l'erreur, j'ai compilé les heures supplémentaires des intéressés dans un fichier Excel et ajouté le résultat Gestime qui montre le décalage.
D'autant que les heures supplémentaires compilées proviennent de Gestime, ainsi que les heures payées. 
Donc comment entre Excel et Gestime avec les mêmes données on n' arrive pas au même résultat ?
J'envoie le fichier en parallèle sur Hangout.

Lucie
