### ISSUE TITLE
Ajout utilisateur

### ISSUE THREAD

**Issue by querel-lucie** [wleberre/gestimes#3]
Salut William,

Je t'ai pas répondu à l'autre issues car on attend la semaine prochaine pour te répondre correctement. En revanche Laurine a bien pu être ajouté sur Gestime mais lorqu'elle essaie de se connecter ça ne marche pas donc elle arrive sur la page de connexion elle met bien son identifiant et mot de passe et rien ne se passe. 
Il y a t-il quelque chose à faire comme il est lié à l'AD ? 

Lucie

**Comment by Serizao** [comment]
On avait vu cela ensemble l'ajout d'utilisateur tu l'avait noté . Plusieurs raisons peuvent en être la cause un utilisateur sans date de début de contrat par exemple ne pourra pas se loguer qui plus est ça dépend aussi de la manière dont tu a ajouté cet utilisateur

**Comment by querel-lucie** [comment]
Oui je le souviens mais je ne pouvais pas ajouter l'utilisateur à ce moment la alors que là je peux c'est comme si ça prenait pas en compte son mot de passe, et il y a bien une date de début de contrat et j'ai ajouté en cliquant sur le bouton "ajouter un utilisateur" et on a rempli tous les champs.

**Comment by Serizao** [comment]
si tu veux utiliser l'active directory alors tu dois importer l'utilisateur 
![capture_d ecran_021318_082711_am](https://user-images.githubusercontent.com/11671895/36137922-a10f5c5c-1097-11e8-883a-0b63b253e40b.jpg)

**Comment by querel-lucie** [comment]
J'ai été dessus mais elle est pas dedans

**Comment by Serizao** [comment]
Ou l'as tu créé dans l'AD ? Quelle est son UO

**Comment by querel-lucie** [comment]
Je l'ai crée dans TKI_USER puis TKI_Business developpement au même endroit que Alice.

**Comment by Serizao** [comment]
Il manquait l'adresse mail dans le profil Active Directory
