### ISSUE TITLE
pas de graphique pour les statistiques utilisateur

### ISSUE THREAD

**Issue by querel-lucie** [wleberre/gestimes#4]
Salut,

Nous avons remarqué que lorsque nous allons dans "exports" puis "statistiques utilisateur" et qu'on choisit une personne, il n'y a plus de graphique ou de camembert. 
Est-il possible de remettre ça ? 

Lucie

**Comment by Serizao** [comment]
Salut,

Peux tu développer me dire les erreur que tu vois dans la console compare les donné attendue au données reçu dis moi les différence que tu remarque. As-tu cherché d'ou ça venais ?
William
